# Generated by Django 3.1.1 on 2020-09-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default='description for the song', max_length=500),
        ),
    ]
