# Generated by Django 3.1.1 on 2020-09-26 00:02

from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=32)),
                ('experience', models.IntegerField(default=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to=system.models.teacher_image)),
                ('teacher_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=18)),
                ('grade', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=system.models.student_image)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.classroom')),
            ],
        ),
    ]
