# Generated by Django 3.1.1 on 2020-09-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='description', max_length=300),
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(default='description', max_length=300),
        ),
    ]
