# Generated by Django 3.1.1 on 2020-09-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200926_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(default='Empty', max_length=300),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(default='Empty', max_length=300),
        ),
    ]
